/* Session-only CSV analysis. No uploads, external requests, or browser persistence. */
'use strict';
const $ = id => document.getElementById(id);
const required = ['Part','WO #','Combo #','Manufacturing Work Center','Estimated Work'];
const partFields = [["Last 12 Month's Usage",'Last 12 months’ usage'],['COLORS','Colors'],['ITEMNO1','ITEMNO1'],['ITEMNO2','ITEMNO2'],['OVERITEMNO','OVERITEMNO'],['Label Length','Label length'],['Label Width','Label width']];
function partInfoHTML(source){return partFields.map(([field,label])=>{const values=[...new Set(source.map(r=>String(r[field]??'').trim()).filter(Boolean))];return values.length?`<div><dt>${escapeHTML(label)}</dt><dd>${values.map(escapeHTML).join(' · ')}</dd></div>`:'';}).filter(Boolean).join('');}
let rows=[], partIndex=new Map(), comboIndex=new Map(), visible=[], centers=[], sortKey='Ship By', sortDirection=-1, expanded=new Set();
const summary=new Map();
function summaryEntry(runs,source,status){const work={};for(const r of runs)for(const [center,hours] of Object.entries(r.work))work[center]=(work[center]||0)+hours;return {Part:source[0].Part,Description:source[0].Description||'',Status:status||'All statuses',runs:new Set(runs.map(r=>r['WO #'])).size,combos:new Set(runs.map(r=>r['Combo #']).filter(Boolean)).size,quantity:runs.reduce((s,r)=>s+number(r['WO Quantity']),0),total:runs.reduce((s,r)=>s+r.total,0),work};}
function downloadCSV(columns,records,filename){const quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const safe=x=>/^[=+\-@\t\r]/.test(String(x))?"'"+x:x;const csv=[columns,...records].map(line=>line.map(x=>quote(typeof x==='string'?safe(x):x)).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderSummary(message){const entries=[...summary.values()];$('summary-section').hidden=!entries.length;if(!entries.length)return;const cols=[...new Set(entries.flatMap(r=>Object.keys(r.work)))].sort();$('summary-status').textContent=message||`${entries.length} parts · Saved totals reflect the status filter when added · Session only`;
  $('summary-table').innerHTML=`<thead><tr><th>Part</th><th>Description</th><th>Status filter</th><th class="num">Work orders</th><th class="num">Combos</th><th class="num">Quantity</th>${cols.map(c=>`<th class="num">${escapeHTML(c)}</th>`).join('')}<th class="num">Total hours</th><th>Actions</th></tr></thead><tbody>${entries.map((r,i)=>`<tr><td>${escapeHTML(r.Part)}</td><td>${escapeHTML(r.Description)}</td><td>${escapeHTML(r.Status)}</td><td class="num">${fmt(r.runs)}</td><td class="num">${fmt(r.combos)}</td><td class="num">${fmt(r.quantity)}</td>${cells(r,cols)}<td class="num">${fmt(r.total)}</td><td><button type="button" class="combo-button" data-remove-summary="${i}" aria-label="Remove ${escapeHTML(r.Part)} from summary">Remove</button></td></tr>`).join('')}</tbody><tfoot><tr><td colspan="5">Combined totals</td><td class="num">${fmt(entries.reduce((s,r)=>s+r.quantity,0))}</td>${cols.map(c=>`<td class="num">${fmt(entries.reduce((s,r)=>s+(r.work[c]||0),0))}</td>`).join('')}<td class="num">${fmt(entries.reduce((s,r)=>s+r.total,0))}</td><td></td></tr></tfoot>`;
}
const number = value => {const n=Number(String(value??'').replace(/,/g,'').trim());return Number.isFinite(n)?n:0;};
const fmt = n => n.toLocaleString(undefined,{maximumFractionDigits:3});
const escapeHTML = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseCSV(text){
  text=text.replace(/^\uFEFF/,'');const records=[];let record=[],field='',quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else if(quoted||field==='')quoted=!quoted;else field+=c;}else if(c===','&&!quoted){record.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;record.push(field);if(record.some(x=>x.trim()))records.push(record);record=[];field='';}else field+=c;}
  if(quoted)throw new Error('The CSV contains an unclosed quoted field.');record.push(field);if(record.some(x=>x.trim()))records.push(record);
  if(!records.length)throw new Error('The CSV is empty.');const headers=records.shift().map(x=>x.trim());const missing=required.filter(h=>!headers.includes(h));if(missing.length)throw new Error('Missing required columns: '+missing.join(', '));
  return records.map((values,i)=>{if(values.length!==headers.length)throw new Error('CSV row '+(i+2)+' has an unexpected number of columns.');return Object.fromEntries(headers.map((h,j)=>[h,values[j].trim()]));});
}
function groupRuns(source){const groups=new Map();for(const r of source){const key=JSON.stringify([r['WO #'],r.Part,r['Combo #']]);if(!groups.has(key))groups.set(key,{...r,work:{},total:0});const g=groups.get(key),center=r['Manufacturing Work Center']||'Unassigned',hours=number(r['Estimated Work']);g.work[center]=(g.work[center]||0)+hours;g.total+=hours;}return [...groups.values()];}
function compare(a,b,key){if(key==='Ship By'){const date=s=>{const m=/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(s);return m?Date.UTC(+m[3],+m[1]-1,+m[2]):0;};return date(a[key])-date(b[key]);}if(key==='total')return a.total-b.total;if(key==='WO Quantity')return number(a[key])-number(b[key]);if(centers.includes(key))return (a.work[key]||0)-(b.work[key]||0);return String(a[key]||'').localeCompare(String(b[key]||''),undefined,{numeric:true});}
function cells(run,columns){return columns.map(c=>`<td class="num">${Object.hasOwn(run.work,c)?fmt(run.work[c]):'<span class="muted">—</span>'}</td>`).join('');}
function detailHTML(combo){const runs=groupRuns(comboIndex.get(combo)||[]);const cols=[...new Set(runs.flatMap(r=>Object.keys(r.work)))].sort();return `<h4>Combo ${escapeHTML(combo)} · ${new Set(runs.map(r=>r.Part)).size} parts · ${fmt(runs.reduce((s,r)=>s+r.total,0))} total estimated hours · All statuses</h4><div class="table-scroll"><table><thead><tr><th>Part</th><th>Description</th><th>WO #</th><th>Status</th><th class="num">Quantity</th>${cols.map(c=>`<th class="num">${escapeHTML(c)}</th>`).join('')}<th class="num">Total hours</th></tr></thead><tbody>${runs.map(r=>`<tr class="${r.Part===$('part').value.trim()?'selected-part':''}"><td>${escapeHTML(r.Part)}</td><td>${escapeHTML(r.Description)}</td><td>${escapeHTML(r['WO #'])}</td><td>${escapeHTML(r.Status)}</td><td class="num">${fmt(number(r['WO Quantity']))}</td>${cells(r,cols)}<td class="num">${fmt(r.total)}</td></tr>`).join('')}</tbody></table></div>`;}
function render(){const part=$('part').value.trim();const source=partIndex.get(part.toLowerCase())||[];const filtered=source.filter(r=>!$('status').value||r.Status===$('status').value);visible=groupRuns(filtered);centers=[...new Set(visible.flatMap(r=>Object.keys(r.work)))].sort();$('results').hidden=!visible.length;$('empty').hidden=!!visible.length;$('export').disabled=!visible.length;
  $('add-summary').disabled=!visible.length;
  if(!visible.length){$('empty').innerHTML=rows.length?`<h2>${part?'No matching work orders':'Choose a part number'}</h2><p>${part?'Select a part from the suggestions or change the status filter.':'Type any portion of a part number to see suggestions.'}</p>`:$('empty').innerHTML;return;}
  $('part-title').textContent=source[0].Part;$('description').textContent=source[0].Description;$('customer').textContent=[...new Set(filtered.map(r=>r.Customer).filter(Boolean))].join(' · ');
  const info=partInfoHTML(source);$('part-info').hidden=!info;$('part-info').innerHTML=info?`<h3>Part information</h3><dl>${info}</dl>`:'';
  $('runs').textContent=fmt(new Set(visible.map(r=>r['WO #'])).size);$('combos').textContent=fmt(new Set(visible.map(r=>r['Combo #']).filter(Boolean)).size);$('quantity').textContent=fmt(visible.reduce((s,r)=>s+number(r['WO Quantity']),0));$('hours').textContent=fmt(visible.reduce((s,r)=>s+r.total,0));
  const totals=Object.fromEntries(centers.map(c=>[c,visible.reduce((s,r)=>s+(r.work[c]||0),0)]));const max=Math.max(...Object.values(totals),0);$('chart').innerHTML=Object.entries(totals).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div class="bar-row"><span>${escapeHTML(c)}</span><div class="bar-track"><div class="bar-fill" style="width:${max?Math.max(0,n/max*100):0}%"></div></div><span class="bar-value">${fmt(n)} h</span></div>`).join('');
  visible.sort((a,b)=>compare(a,b,sortKey)*sortDirection);const columns=['Ship By','WO #','Combo #','WO Quantity','Status',...centers,'total'];const labels={'WO Quantity':'Quantity',total:'Total hours'};
  $('history').innerHTML=`<thead><tr>${columns.map((c,i)=>`<th scope="col" data-sort="${i}" tabindex="0" aria-sort="${sortKey===c?(sortDirection===1?'ascending':'descending'):'none'}" class="${i===3||i>=5?'num':''}">${escapeHTML(labels[c]||c)}${sortKey===c?(sortDirection===1?' ▴':' ▾'):''}</th>`).join('')}</tr></thead><tbody>${visible.map((r,i)=>`<tr><td>${escapeHTML(r['Ship By'])||'<span class="muted">—</span>'}</td><td>${escapeHTML(r['WO #'])}</td><td>${r['Combo #']?`<button class="combo-button" data-run="${i}" aria-expanded="${expanded.has(i)}" aria-controls="combo-detail-${i}">${expanded.has(i)?'−':'+'} ${escapeHTML(r['Combo #'])}</button>`:'<span class="muted">—</span>'}</td><td class="num">${fmt(number(r['WO Quantity']))}</td><td>${escapeHTML(r.Status)}</td>${cells(r,centers)}<td class="num">${fmt(r.total)}</td></tr>${expanded.has(i)?`<tr class="detail" id="combo-detail-${i}"><td colspan="${columns.length}">${detailHTML(r['Combo #'])}</td></tr>`:''}`).join('')}</tbody><tfoot><tr><td colspan="3">Selected part totals</td><td class="num">${$('quantity').textContent}</td><td></td>${centers.map(c=>`<td class="num">${fmt(totals[c])}</td>`).join('')}<td class="num">${$('hours').textContent}</td></tr></tfoot>`;
}
function suggestions(){const query=$('part').value.trim().toLowerCase();$('parts').innerHTML=[...partIndex.entries()].filter(([key])=>key.includes(query)).slice(0,100).map(([,values])=>`<option value="${escapeHTML(values[0].Part)}">${escapeHTML(values[0].Description)}</option>`).join('');}
if(typeof document!=='undefined'){
  const setTheme=dark=>{document.documentElement.dataset.theme=dark?'dark':'light';$('theme-toggle').setAttribute('aria-pressed',String(dark));};
  let savedTheme;try{savedTheme=localStorage.getItem('part-hours-theme');}catch{}
  setTheme(savedTheme?savedTheme==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches);
  $('theme-toggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';setTheme(dark);try{localStorage.setItem('part-hours-theme',dark?'dark':'light');}catch{}});
  $('upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('file-status').classList.remove('error');$('file-status').textContent='Reading '+file.name+'…';try{const parsed=parseCSV(await file.text());const valid=parsed.filter(r=>r.Part&&r['WO #']);if(!valid.length)throw new Error('No rows contain both a part number and a work order.');rows=valid;partIndex=new Map();comboIndex=new Map();for(const r of rows){const key=r.Part.toLowerCase();if(!partIndex.has(key))partIndex.set(key,[]);partIndex.get(key).push(r);if(r['Combo #']){if(!comboIndex.has(r['Combo #']))comboIndex.set(r['Combo #'],[]);comboIndex.get(r['Combo #']).push(r);}}
  $('part').disabled=false;$('status').disabled=false;$('status').innerHTML='<option value="">All statuses</option>'+[...new Set(rows.map(r=>r.Status))].sort().map(s=>`<option value="${escapeHTML(s)}">${escapeHTML(s)||'Unspecified'}</option>`).join('');$('part').value='';expanded.clear();$('file-status').textContent=`${file.name} · ${fmt(rows.length)} operation rows · ${fmt(partIndex.size)} parts${parsed.length!==rows.length?' · '+(parsed.length-rows.length)+' rows without a part or WO omitted':''} · Session only`;suggestions();render();$('part').focus();}catch(err){$('file-status').textContent=err.message;$('file-status').classList.add('error');}finally{e.target.value='';}});
  $('part').addEventListener('input',()=>{expanded.clear();suggestions();render();});$('status').addEventListener('change',()=>{expanded.clear();render();});
  $('add-summary').addEventListener('click',()=>{if(!visible.length)return;const source=partIndex.get($('part').value.trim().toLowerCase());const entry=summaryEntry(visible,source,$('status').value);const key=entry.Part.toLowerCase();const replacing=summary.has(key);summary.set(key,entry);renderSummary(`${entry.Part} ${replacing?'updated in':'added to'} summary · ${summary.size} parts · Session only`);});
  $('summary-table').addEventListener('click',e=>{const button=e.target.closest('[data-remove-summary]');if(!button)return;const key=[...summary.keys()][Number(button.dataset.removeSummary)];summary.delete(key);renderSummary();});
  $('clear-summary').addEventListener('click',()=>{summary.clear();renderSummary();});
  $('export-summary').addEventListener('click',()=>{const entries=[...summary.values()];if(!entries.length)return;const cols=[...new Set(entries.flatMap(r=>Object.keys(r.work)))].sort();downloadCSV(['Part','Description','Status filter','Work orders','Combos','Quantity',...cols,'Total hours'],[...entries.map(r=>[r.Part,r.Description,r.Status,r.runs,r.combos,r.quantity,...cols.map(c=>r.work[c]||0),r.total]),['Combined totals','','','','',entries.reduce((s,r)=>s+r.quantity,0),...cols.map(c=>entries.reduce((s,r)=>s+(r.work[c]||0),0)),entries.reduce((s,r)=>s+r.total,0)]],'parts-hours-summary.csv');});
  $('history').addEventListener('click',e=>{const button=e.target.closest('[data-run]');if(button){const i=Number(button.dataset.run);expanded.has(i)?expanded.delete(i):expanded.add(i);render();return;}const th=e.target.closest('[data-sort]');if(th){const key=['Ship By','WO #','Combo #','WO Quantity','Status',...centers,'total'][Number(th.dataset.sort)];sortDirection=sortKey===key?-sortDirection:1;sortKey=key;expanded.clear();render();}});
  $('history').addEventListener('keydown',e=>{if(e.target.matches('[data-sort]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.target.click();}});
  $('export').addEventListener('click',()=>{const columns=['Part','Ship By','WO #','Combo #','WO Quantity','Status',...centers,'Total hours'];const quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const safe=x=>/^[=+\-@\t\r]/.test(String(x))?"'"+x:x;const csv=[columns,...visible.map(r=>[r.Part,r['Ship By'],r['WO #'],r['Combo #'],number(r['WO Quantity']),r.Status,...centers.map(c=>r.work[c]??''),r.total])].map(line=>line.map(x=>quote(typeof x==='string'?safe(x):x)).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=$('part').value.replace(/[^a-zA-Z0-9_-]/g,'_')+'-hours.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
if(typeof module!=='undefined')module.exports={parseCSV,groupRuns,number,partInfoHTML,summaryEntry};
